### ISSUE TITLE
How to get pretrain_clip/RN50.pt

### ISSUE THREAD

**Issue by ZDDDYuan** [HilbertXu/CROG#1]
I have no idea how to get the pretained CLIP model based ResNet50, even though I have searched the Internet for it.

**Comment by vineet2104** [comment]
Can you please point me to the RN50.pt checkpoint?

**Comment by ZDDDYuan** [comment]
you can get it in the clip.py file of the official CLIP code, which gives download links to all the pre-trained model .pt files.

> Can you please point me to the RN50.pt checkpoint?
